export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  SUB_USER = 'SUB_USER',
}

export enum UserStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ACTIVE = 'ACTIVE',
  LOCKED = 'LOCKED',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
}

export enum CampaignFrequency {
  LOW = '10-100',
  MEDIUM = '100-1000',
  HIGH = '1000+',
}

export enum SignupRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum TransactionType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  REVERSAL = 'REVERSAL',
  LOCK = 'LOCK',
  UNLOCK = 'UNLOCK',
}

export enum ModuleType {
  UNIFIED_BALANCE = 'UNIFIED_BALANCE',
  DISCOVERY = 'DISCOVERY',
  INSIGHTS = 'INSIGHTS',
  AUDIENCE_OVERLAP = 'AUDIENCE_OVERLAP',
  TIE_BREAKER = 'TIE_BREAKER',
  SOCIAL_SENTIMENTS = 'SOCIAL_SENTIMENTS',
  INFLUENCER_COLLAB_CHECK = 'INFLUENCER_COLLAB_CHECK',
  PAID_COLLABORATION = 'PAID_COLLABORATION',
  CAMPAIGN_TRACKING = 'CAMPAIGN_TRACKING',
  MENTION_TRACKING = 'MENTION_TRACKING',
  COMPETITION_ANALYSIS = 'COMPETITION_ANALYSIS',
  INFLUENCER_GROUP = 'INFLUENCER_GROUP',
  EXPORT = 'EXPORT',
}

export enum ActionType {
  MANUAL_ALLOCATION = 'MANUAL_ALLOCATION',
  INFLUENCER_SEARCH = 'INFLUENCER_SEARCH',
  INFLUENCER_UNBLUR = 'INFLUENCER_UNBLUR',
  INFLUENCER_INSIGHT = 'INFLUENCER_INSIGHT',
  INFLUENCER_EXPORT = 'INFLUENCER_EXPORT',
  PROFILE_UNLOCK = 'PROFILE_UNLOCK',
  REPORT_GENERATION = 'REPORT_GENERATION',
  REPORT_REFRESH = 'REPORT_REFRESH',
  ACCOUNT_EXPIRY = 'ACCOUNT_EXPIRY',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
  INSIGHT_UNLOCK = 'INSIGHT_UNLOCK',
  INSIGHT_REFRESH = 'INSIGHT_REFRESH',
}

export enum PlatformType {
  INSTAGRAM = 'INSTAGRAM',
  YOUTUBE = 'YOUTUBE',
  TIKTOK = 'TIKTOK',
  LINKEDIN = 'LINKEDIN',
}

export enum EmailStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  BOUNCED = 'BOUNCED',
}

export * from './team.enums';
