export enum InternalRoleType {
  CLIENT = 'CLIENT',
  BUSINESS_TEAM = 'BUSINESS_TEAM',
  FINANCE_TEAM = 'FINANCE_TEAM',
  SALES_TEAM = 'SALES_TEAM',
  SUPPORT_TEAM = 'SUPPORT_TEAM',
  TECHNICAL_TEAM = 'TECHNICAL_TEAM',
}

export enum FeatureName {
  INFLUENCER_DISCOVERY = 'INFLUENCER_DISCOVERY',
  INFLUENCER_INSIGHTS = 'INFLUENCER_INSIGHTS',
  PAID_COLLABORATION = 'PAID_COLLABORATION',
  AUDIENCE_OVERLAP = 'AUDIENCE_OVERLAP',
  INFLUENCER_TIE_BREAKER = 'INFLUENCER_TIE_BREAKER',
  PAID_COMPARISON = 'PAID_COMPARISON',
  CUSTOM_ER_CALCULATOR = 'CUSTOM_ER_CALCULATOR',
  SOCIAL_SENTIMENTS = 'SOCIAL_SENTIMENTS',
  INFLUENCER_COLLAB_CHECK = 'INFLUENCER_COLLAB_CHECK',
  MENTION_TRACKING = 'MENTION_TRACKING',
  CAMPAIGN_TRACKING = 'CAMPAIGN_TRACKING',
  INFLUENCERS_GROUP = 'INFLUENCERS_GROUP',
  COMPETITION_ANALYSIS = 'COMPETITION_ANALYSIS',
}

export enum ActionName {
  EXCEL_REPORT_DOWNLOAD = 'EXCEL_REPORT_DOWNLOAD',
  CRM_INVITE_FORM = 'CRM_INVITE_FORM',
}
